github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

helpers:
  "bin/helper": "$GOMOD/cmd/helper"

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/app-monitoring-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/yourkit"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
  - registry: docker.io
    username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
    password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name: YourKit Java Agent
  id:   yourkit-java
  uses: docker://ghcr.io/paketo-buildpacks/actions/yourkit-dependency:main
  with:
    arch: amd64
- name: YourKit Java Agent ARM64
  id:   yourkit-java
  uses: docker://ghcr.io/paketo-buildpacks/actions/yourkit-dependency:main
  with:
    arch: arm64
